name: dshell_example
version: 1.0.0
homepage: https://github.com/bsutton/dshell
description: An API and dev environment for writing console apps/scripts using dart. e.g. allows you to build bash style scripts with dart.
environment: 
  sdk: '>=2.9.0-13.0.dev <3.0.0'
dependencies: 
  dshell: 
    path: ..
